name: Daily Election Results Scrape (Conditional)

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check ENABLE_RESULTS secret
        run: |
          if [ "${{ secrets.ENABLE_RESULTS }}" != "true" ]; then
            echo "ENABLE_RESULTS is not true. Skipping run."
            exit 0
          fi

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python scraper/scrape_results.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin master --rebase
          git add data/raw/manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "update results manifest"
            git push origin master
          else
            echo "No changes to commit"
          fi
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
