name: Daily Election Results Scrape (Conditional)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2:00 UTC (10pm ET)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests

      - name: Run scraper if ENABLE_RESULTS is true
        env:
          ENABLE_RESULTS: ${{ secrets.ENABLE_RESULTS }}
        run: |
          if [ "$ENABLE_RESULTS" = "true" ]; then
            python scraper/scrape_results.py
          else
            echo "Election scraper is disabled."
          fi

      - name: Commit updated manifest (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/raw/manifest.json
          git diff --cached --quiet || git commit -m "update results manifest"
        continue-on-error: true  # Prevent workflow failure if no changes

      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}